### ISSUE TITLE
Add attachments to tasks

### ISSUE THREAD

**Issue by odenypeter** [toladata/TolaWork#250]
Allow users to add attachments to tasks during creation or editing.

**Comment by karrla** [comment]
ProgrammingError at /tasks/tasks/
(1146, "Table 'helpdesk.tasks_taskattachment' doesn't exist")

**Comment by odenypeter** [comment]
This error is already fixed. The link to task is now working

**Comment by karrla** [comment]
Can't add attachments to Tasks, only to new tasks.

**Comment by odenypeter** [comment]
done

**Comment by karrla** [comment]
I still don't see how to add an attachment to a task: 


![uploads/4747a367-4478-4a44-b463-c5ba19e9824d/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4747a367-4478-4a44-b463-c5ba19e9824d%2Fblob)
